[workspace]
members = [
  # core
  "leptos",
  "leptos_dom",
  "leptos_core",
  "leptos_config",
  "leptos_macro",
  "leptos_reactive",
  "leptos_server",

  # integrations
  "integrations/actix",
  "integrations/axum",

  # libraries
  "meta",
  "router",

  # examples
  "examples/counter",
  "examples/counter-isomorphic",
  "examples/counters",
  "examples/counters-stable",
  "examples/fetch",
  "examples/hackernews",
  "examples/hackernews-axum",
  "examples/parent-child",
  "examples/router",
  "examples/todomvc",
  "examples/todo-app-sqlite",
  "examples/todo-app-sqlite-axum",
  "examples/todo-app-cbor",
  "examples/view-tests",
]
exclude = ["benchmarks"]

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[workspace.metadata.cargo-all-features]
skip_feature_sets = [
  [
    "csr",
    "ssr",
  ],
  [
    "csr",
    "hydrate",
  ],
  [
    "ssr",
    "hydrate",
  ],
  [
    "serde",
    "serde-lite",
  ],
  [
    "serde-lite",
    "miniserde",
  ],
  [
    "serde",
    "miniserde",
  ],
]
